---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(magrittr)
library(sf)
library(tmap)
library(igraph)
```


```{r}
road <- st_read("ToyData/RiveraNetwork_Toy_Cleaned.shp")

road %<>% mutate(Id = seq(1, dim(road)[1], 1), 
                 Length = st_length(road)) %>% #To have a proxy to impedance
         mutate(Length = as.numeric(Length)) %>% 
         select(Id, Length)
```

```{r}
plot(st_geometry(road))
```


```{r}
GraphResult <- data.frame(Source = c(NULL), 
                          Target = c(NULL), 
                          weight  = c(NULL))
Nodes <- data.frame(c())


##See how to change to apply logic or to map logic.
for (i in 1:dim(road)[1]){
  
  TempGraphResult <- data.frame(Source = c(0), 
                                Target = c(0), 
                                weight  = c(0))
  
  TempLink <- road %>% slice(i)
  TempNodes <- st_coordinates(TempLink) %>% as.data.frame()
  
  TempNodes <- TempNodes %>%
      mutate(Id = paste(as.character(X),
                        as.character(Y),
                        sep="-"))
  
  TempGraphResult$Source[1] <- TempNodes$Id[1]
  TempGraphResult$Target[1] <- TempNodes$Id[dim(TempNodes)[1]] # KEY
  TempGraphResult$weight [1] <- road$Length[i]
  
  GraphResult <- rbind(GraphResult, TempGraphResult)
  
  TempNodes <- TempNodes %>% slice(1,dim(TempNodes)[1])
  
  Nodes <- rbind(Nodes, TempNodes)
}

## 

MyIgraph <- graph_from_data_frame(GraphResult) 


```

```{r}
DistancesMatrix <- distances(MyIgraph)
DistancesMatrix <- as.data.frame(DistancesMatrix)

NamesRow <- row.names(DistancesMatrix)
NamesColumns <- names(DistancesMatrix)
summary(NamesRow==NamesColumns)

DistancesMatrix$NodesOrigin <- NamesRow

DistancesLongFormat <- pivot_longer(DistancesMatrix, cols = -NodesOrigin,
                                    names_to = "NodeDestination",
                                    values_to = "TravelTime")

####

NodesSummary <- Nodes %>% 
  group_by(Id) %>% 
  summarise(TotalLines = n(), Long = min(X), Lat = min(Y)) 
  
```


```{r}
#write_delim(DistancesLongFormat, "ToyData/Distances_Toy.csv", delim = ";")
#write_delim(NodesSummary, "ToyData/Nodes_Toy.csv", delim = ";")
```


```{r}
distances(MyIgraph, "-55.5254843--30.896805", "-55.5254843--30.896805")
```

```{r}
distances(MyIgraph, "-55.5254843--30.896805", "-55.5604783--30.8988728")
```

```{r}
distances(MyIgraph, "-55.5388404--30.8946788", "-55.5335082--30.9087207")
```

```{r}
distances(MyIgraph, "-55.5335082--30.9087207", "-55.5388404--30.8946788")
```



```{r}
DistancesLongFormat %>% 
  filter(NodesOrigin == "-55.5483514--30.8848521") %>% 
  filter(NodeDestination == "-55.5477998--30.8852398")
```



```{r}
DistancesLongFormat %>% 
  filter(NodesOrigin == "-55.5477998--30.8852398") %>% 
  filter(NodeDestination == "-55.5483514--30.8848521")
```



```{r}


DistancesLongFormat %>% 
  filter(NodesOrigin == "-55.5483514--30.8848521") %>% 
  filter(NodeDestination == "-55.5480204--30.8853884")
```

```{r}


DistancesLongFormat %>% 
  filter(NodesOrigin == "-55.5480204--30.8853884") %>% 
  filter(NodeDestination == "-55.5483514--30.8848521")
```