---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
library(magrittr)
library(sf)
library(tmap)
library(RColorBrewer)
```

```{r}
PopulationOA <- read_delim("../TravelTimeCalculations/Results/Fraybentos/MatrixOA_Fraybentos.csv",
                           delim = " ")

PopulationPolygon <- st_read("../TravelTimeCalculations/Results/Fraybentos/Pouplation_Fraybentos.shp")

PopulationPolygon %<>% select(Node) %>% left_join(PopulationOA)
```

```{r}
Oportunity <- PopulationOA
MapOportunity <- PopulationPolygon

MapTitle <- "Oportunidades Acumuladas"

X_Lab <- "Población (Porcentaje Acumulado)"
Y_Lab <- "Cantidad de Espacio Público"

Subtitle <- "Accesibilidad"
Subtitle200 <- paste(Subtitle,"a 200 metros", sep = " ")
Subtitle400 <- paste(Subtitle,"a 400 metros", sep = " ")
Subtitle600 <- paste(Subtitle,"a 600 metros", sep = " ")
Subtitle1000 <- paste(Subtitle,"a 1 Km", sep = " ")

Caption <- "Proyecto OPP"
```

```{r}
Breaks = c(0, 0.1, 2.1, 4.1, 6.1, 8.1, 10.1, 12.1)
Labels = c("Ninguna","0 - 2", "2 - 4", "4 - 6", "6 - 8", "8 - 10","10 - 12")
```


## 0.2 Km


```{r}
Gap <- Oportunity %>% select(Population, Gap = Gap_200) %>% 
  group_by(Gap) %>% 
  summarise(Population = sum(Population, na.rm = TRUE)) %>% 
  arrange(Gap) %>% 
  filter(Gap > 0)

Total <- sum(Gap$Population)
Gap$PopAcum <- cumsum(Gap$Population)
Gap$PorAcum <- Gap$PopAcum/Total
```

```{r}
Gap
```


```{r}

Plot200 <- ggplot(data = Gap) + 
  geom_line(aes(x = PorAcum, y = Gap), col = "#8da0cb", size = 1.5) +
  geom_point(aes(x = PorAcum, y = Gap), col = "#a6d854", size = 3) + 
  labs(subtitle = Subtitle200, caption = Caption) + 
  xlab(X_Lab) + ylab(Y_Lab) +
  scale_x_continuous(breaks = seq(0,1,0.1),
                     labels = paste(seq(0,1,0.1)*100,"%")) +
  scale_y_continuous(breaks = seq(1,10,1)) +
  theme_light()

Plot200
```

```{r}
Map200 <- tm_shape(MapOportunity) + 
  tm_polygons(col = "Gap_200", title = MapTitle, 
              palette = "-RdYlGn",
              breaks = Breaks, 
              labels = Labels) +
  tm_layout(legend.position = c(0.1 ,0.1)) +
   tm_compass(size = 1.5, position = c(0, 0.9)) + 
   tm_scale_bar(position = c(0.15,0, size = 3))

Map200
```

## 0.4 Km

```{r}
Gap <- Oportunity %>% select(Population, Gap = Gap_400) %>% 
  group_by(Gap) %>% 
  summarise(Population = sum(Population, na.rm = TRUE)) %>% 
  arrange(Gap) %>% 
  filter(Gap > 0)

Total <- sum(Gap$Population)
Gap$PopAcum <- cumsum(Gap$Population)
Gap$PorAcum <- Gap$PopAcum/Total
```

```{r}
Gap
```

```{r}

Plot400 <- ggplot(data = Gap) + 
  geom_line(aes(x = PorAcum, y = Gap), col = "#8da0cb", size = 1.5) +
  geom_point(aes(x = PorAcum, y = Gap), col = "#a6d854", size = 3) + 
  labs(subtitle = Subtitle400, caption = Caption) + 
  xlab(X_Lab) + ylab(Y_Lab) +
  scale_x_continuous(breaks = seq(0,1,0.1),
                     labels = paste(seq(0,1,0.1)*100,"%")) +
  scale_y_continuous(breaks = seq(1,10,1)) +
  theme_light()

Plot400
```

```{r}
Map400 <- tm_shape(MapOportunity) + 
  tm_polygons(col = "Gap_400", title = MapTitle, 
              palette = "-RdYlGn",
              breaks = Breaks, 
              labels = Labels) +
  tm_layout(legend.position = c(0.1 ,0.1)) +
   tm_compass(size = 1.5, position = c(0, 0.9)) + 
   tm_scale_bar(position = c(0.15,0, size = 3))

Map400
```


## 0.6 km

```{r}
Gap <- Oportunity %>% select(Population, Gap = Gap_600) %>% 
  group_by(Gap) %>% 
  summarise(Population = sum(Population, na.rm = TRUE)) %>% 
  arrange(Gap) %>% 
  filter(Gap > 0)

Total <- sum(Gap$Population)
Gap$PopAcum <- cumsum(Gap$Population)
Gap$PorAcum <- Gap$PopAcum/Total
```

```{r}
Gap
```

```{r}
Plot600 <- ggplot(data = Gap) + 
  geom_line(aes(x = PorAcum, y = Gap), col = "#8da0cb", size = 1.5) +
  geom_point(aes(x = PorAcum, y = Gap), col = "#a6d854", size = 3) + 
  labs(subtitle = Subtitle600, caption = Caption) + 
  xlab(X_Lab) + ylab(Y_Lab) +
  scale_x_continuous(breaks = seq(0,1,0.1),
                     labels = paste(seq(0,1,0.1)*100,"%")) +
  scale_y_continuous(breaks = seq(1,10,1)) +
  theme_light()

Plot600
```

```{r}
Map600 <- tm_shape(MapOportunity) + 
  tm_polygons(col = "Gap_600", title = MapTitle, 
              palette = "-RdYlGn",
              breaks = Breaks, 
              labels = Labels) +
  tm_layout(legend.position = c(0.1 ,0.1)) +
   tm_compass(size = 1.5, position = c(0, 0.9)) + 
   tm_scale_bar(position = c(0.15,0, size = 3))

Map600
```

## 1 Km

```{r}
Gap <- Oportunity %>% select(Population, Gap = Gap_1000) %>% 
  group_by(Gap) %>% 
  summarise(Population = sum(Population, na.rm = TRUE)) %>% 
  arrange(Gap) %>% 
  filter(Gap > 0)

Total <- sum(Gap$Population)
Gap$PopAcum <- cumsum(Gap$Population)
Gap$PorAcum <- Gap$PopAcum/Total
```

```{r}
Gap
```

```{r}
Plot1000 <- ggplot(data = Gap) + 
  geom_line(aes(x = PorAcum, y = Gap), col = "#8da0cb", size = 1.5) +
  geom_point(aes(x = PorAcum, y = Gap), col = "#a6d854", size = 3) + 
  labs(subtitle = Subtitle1000, caption = Caption) + 
  xlab(X_Lab) + ylab(Y_Lab) +
  scale_x_continuous(breaks = seq(0,1,0.1),
                     labels = paste(seq(0,1,0.1)*100,"%")) +
  scale_y_continuous(breaks = seq(1,10,1)) +
  theme_light()

Plot1000
```


```{r}
Map1000 <- tm_shape(MapOportunity) + 
  tm_polygons(col = "Gap_1000", title = MapTitle, 
              palette = "-RdYlGn",
              breaks = Breaks, 
              labels = Labels) +
  tm_layout(legend.position = c(0.1 ,0.1))+
   tm_compass(size = 1.5, position = c(0, 0.9)) + 
   tm_scale_bar(position = c(0.15,0, size = 3))

Map1000
```


# Imprimir Resultados

```{r}

# ggsave("ResultFraybentos/Ojiva200_Fraybentos.png", Plot200)
# ggsave("ResultFraybentos/Ojiva400_Fraybentos.png", Plot400)
# ggsave("ResultFraybentos/Ojiva600_Fraybentos.png", Plot600)
# ggsave("ResultFraybentos/Ojiva1000_Fraybentos.png", Plot1000)
# 
# tmap_save(Map200, "ResultFraybentos//Map200_Fraybentos.png")
# tmap_save(Map400, "ResultFraybentos//Map400_Fraybentos.png")
# tmap_save(Map600, "ResultFraybentos//Map600_Fraybentos.png")
# tmap_save(Map1000, "ResultFraybentos//Map1000_Fraybentos.png")
```

