---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
library(magrittr)
library(sf)
library(tmap)
library(RColorBrewer)
```

```{r}
PopulationOA <- read_delim("../TravelTimeCalculations/ToyData/ResultForAnalysis_TOY/MatrixOA.csv", delim = " ")

PopulationPolygon <- st_read("../TravelTimeCalculations/ToyData/ResultForAnalysis_TOY/PopulationRivera.shp")

PopulationPolygon %<>% select(Node) %>% left_join(PopulationOA)
```

```{r}
Oportunity <- PopulationOA
MapOportunity <- PopulationPolygon

MapTitle <- "Accesibilidad - Oportunidades Acumuladas"

X_Lab <- "Población (Porcentaje Acumulado)"
Y_Lab <- "Cantidad de Espacio Público"

Subtitle <- "Accesibilidad"
Subtitle500 <- paste(Subtitle,"a 500 metros", sep = " ")
Subtitle1000 <- paste(Subtitle,"a 1 Km", sep = " ")
Subtitle1500 <- paste(Subtitle,"a 1.5 Km", sep = " ")

Caption <- "Proyecto OPP (Borrador)"
```

## 0.5 Km

```{r}
Gap <- Oportunity %>% select(Population, Gap = Gap_500) %>% 
  group_by(Gap) %>% 
  summarise(Population = sum(Population)) %>% 
  arrange(Gap) %>% 
  filter(Gap > 0)

Total <- sum(Gap$Population)
Gap$PopAcum <- cumsum(Gap$Population)
Gap$PorAcum <- Gap$PopAcum/Total
```

```{r}
ggplot(data = Gap) + 
  geom_line(aes(x = PorAcum, y = Gap), col = "#8da0cb", size = 1.5) +
  geom_point(aes(x = PorAcum, y = Gap), col = "#a6d854", size = 3) + 
  labs(subtitle = Subtitle500, caption = Caption) + 
  xlab(X_Lab) + ylab(Y_Lab) +
  scale_x_continuous(breaks = seq(0,1,0.1),
                     labels = paste(seq(0,1,0.1)*100,"%")) +
  scale_y_continuous(breaks = seq(1,10,1)) +
  theme_light()
```

```{r}
tm_shape(MapOportunity) + 
  tm_polygons(col = "Gap_500", title = MapTitle, palette = "Blues") +
  tm_layout(legend.position = c(0.6 ,0.75)) +
   tm_compass(size = 1.5, position = c(0, 0.9)) + 
   tm_scale_bar(position = c(0.15,0, size = 3))
```


## 1 Km

```{r}
Gap <- Oportunity %>% select(Population, Gap = Gap_1000) %>% 
  group_by(Gap) %>% 
  summarise(Population = sum(Population)) %>% 
  arrange(Gap) %>% 
  filter(Gap > 0)

Total <- sum(Gap$Population)
Gap$PopAcum <- cumsum(Gap$Population)
Gap$PorAcum <- Gap$PopAcum/Total
```

```{r}
ggplot(data = Gap) + 
  geom_line(aes(x = PorAcum, y = Gap), col = "#8da0cb", size = 1.5) +
  geom_point(aes(x = PorAcum, y = Gap), col = "#a6d854", size = 3) + 
  labs(subtitle = Subtitle1000, caption = Caption) + 
  xlab(X_Lab) + ylab(Y_Lab) +
  scale_x_continuous(breaks = seq(0,1,0.1),
                     labels = paste(seq(0,1,0.1)*100,"%")) +
  scale_y_continuous(breaks = seq(1,10,1)) +
  theme_light()
```


```{r}
tm_shape(MapOportunity) + 
  tm_polygons(col = "Gap_1000", title = MapTitle, palette = "Blues") +
  tm_layout(legend.position = c(0.6 ,0.75)) +
   tm_compass(size = 1.5, position = c(0, 0.9)) + 
   tm_scale_bar(position = c(0.15,0, size = 3))
```

## 1.5 km

```{r}
Gap <- Oportunity %>% select(Population, Gap = Gap_1500) %>% 
  group_by(Gap) %>% 
  summarise(Population = sum(Population)) %>% 
  arrange(Gap) %>% 
  filter(Gap > 0)

Total <- sum(Gap$Population)
Gap$PopAcum <- cumsum(Gap$Population)
Gap$PorAcum <- Gap$PopAcum/Total
```

```{r}
ggplot(data = Gap) + 
  geom_line(aes(x = PorAcum, y = Gap), col = "#8da0cb", size = 1.5) +
  geom_point(aes(x = PorAcum, y = Gap), col = "#a6d854", size = 3) + 
  labs(subtitle = Subtitle1500, caption = Caption) + 
  xlab(X_Lab) + ylab(Y_Lab) +
  scale_x_continuous(breaks = seq(0,1,0.1),
                     labels = paste(seq(0,1,0.1)*100,"%")) +
  scale_y_continuous(breaks = seq(1,12,1)) +
  theme_light()
```

```{r}
tm_shape(MapOportunity) + 
  tm_polygons(col = "Gap_1500", title = MapTitle, palette = "Blues") +
  tm_layout(legend.position = c(0.6 ,0.75)) +
   tm_compass(size = 1.5, position = c(0, 0.9)) + 
   tm_scale_bar(position = c(0.15,0, size = 3))
```


```{r}

```

